### ISSUE TITLE
Error bei Import von WikiPage Dateien

### ISSUE THREAD

**Issue by LeaS2** [LeaS2/Explainable_NLP#1]
Hey Nils, 
in test.py findest du unseren Code für das PreProcessing der Feverous Daten. 
Der Code wirft einen Error "ModuleNotFoundError: No module named 'wiki_list', wenn die zweite Zeile eingebunden werden soll, obwohl die Files in den richtigen Ordnern vorhanden sind. Wir haben auch schon versucht eine neue Environment aufzusetzen, aber einige der Bibliotheken sind nicht mehr in der benötigten angegebenen Version vorhanden. 
Hast du einen Vorschlag, was wir sonst noch ausprobieren könnten? 
Liebe Grüße 
Lea & Max

**Comment by nfelnlp** [comment]
Hi Lea,
wiki_list ist eine lokale Datei in [src/feverous/database](https://github.com/LeaS2/Explainable_NLP/tree/main/src/feverous/database).
Ich schätze, dass es ein Problem mit dem PYTHONPATH gibt: Um das aktuelle Directory hinzuzufügen, müsstest du folgendes machen:
```bash
export PYTHONPATH=`pwd`
```
Mehr dazu hier: https://stackoverflow.com/a/2326045/6788442 
und hier: https://stackoverflow.com/a/61532947/6788442

Falls ihr PyCharm benutzt, hilft häufig auch das `src` Directory als "Sources Root" zu markieren (bekommt dann eine blaue Farbe).

wiki_list ist kein Package oder Requirement, also kann es eigentlich nur an der Struktur des Repos bzw. der PYTHONPATH-Konfiguration liegen.

Lasst mich wissen, ob ihr damit weiterkommt.

**Comment by B43M** [comment]
Hi Nils,
ich hab mich da heute mal rangesetzt und das mit dem PATH hab irgendwie nicht wirklich verstanden, aber ich bin jetzt einfach auf PyCharm umgestiegen und somit dem Problem erstmal aus dem Weg gegangen 😄 
Jetzt können wir uns neue Probleme suchen und müssen uns nicht mit sowas rumschlagen. Vielen Dank!
